import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import ThemeProviderAll from "./componts/themeprovider";
import Navibar from "./componts/navebar";
import Footer from "./componts/footer";
import ScrollToTopButton from "./scrolltotop";
import { Toaster } from "@/components/ui/sonner";
import ToggleCartButton from "./componts/basketcart/ToggleCartButton";
import { CartProvider } from "./componts/basketcart/CartContext";
import CartSidebar from "./componts/basketcart/CartSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clone Dermactive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ThemeProviderAll> */}
        <CartProvider>
          <Navibar />
          {children}
          <CartSidebar />
          <ToggleCartButton />
          <ScrollToTopButton />
          <Footer />
          <Toaster />
        </CartProvider>
        {/* </ThemeProviderAll> */}
      </body>
    </html>
  );
}
