import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderAll from "./componts/themeprovider";
import Navibar from "./componts/navebar";
import Footer from "./componts/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clone Dermactive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderAll>
          <Navibar />
          {children}
          <Footer />
        </ThemeProviderAll>
      </body>
    </html>
  );
}
