import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderAll from "./componts/themeprovider";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Clone Dermactive</title>
        <meta name="description" content="My awesome website" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderAll>{children}</ThemeProviderAll>
      </body>
    </html>
  );
}
